# syntax=docker/dockerfile:1
FROM node:12-alpine

# RUN apk add --no-cache python2 g++ make
# WORKDIR /app
# COPY . .
# RUN yarn install --production
CMD ["echo", "Hello world testing 1 2 3"]
# EXPOSE 3000
